# Generated by Django 5.0.2 on 2024-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdetails',
            name='auditorname',
            field=models.CharField(default='default', max_length=256),
        ),
    ]
