# Generated by Django 5.0.2 on 2024-03-24 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_stocktype_remove_stock_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.AddField(
            model_name='stocktype',
            name='category',
            field=models.CharField(choices=[('ELC', 'Electronics'), ('FUR', 'Furniture')], default='ELC', max_length=3),
        ),
        migrations.AlterField(
            model_name='auditdetails',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
