# Generated by Django 5.0.2 on 2024-03-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_remove_stock_category_stocktype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdetails',
            name='auditorname',
            field=models.CharField(default='auditor', max_length=256),
        ),
        migrations.AlterField(
            model_name='auditdetails',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('SDMG', 'Slightly damaged'), ('BRKN', 'Broken'), ('WRKN', 'Working'), ('PWRK', 'Partially working'), ('NWRK', 'Not working')], max_length=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='category',
            field=models.CharField(choices=[('ELC', 'Electronics'), ('FUR', 'Furniture')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADT', 'Auditor'), ('CDN', 'Custodian'), ('HOD', 'Head of Department')], max_length=3),
        ),
    ]
