# Generated by Django 5.0.2 on 2024-04-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_auditdetails_auditorname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdetails',
            old_name='auditorname',
            new_name='auditor_name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='auditdetails',
            new_name='audit_details',
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditdetails',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('SDMG', 'Slightly damaged'), ('BRKN', 'Broken')], max_length=4),
        ),
    ]
