# Generated by Django 5.0.2 on 2024-04-07 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_rename_auditorname_auditdetails_auditor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='bill_no',
            field=models.CharField(default='0000.00', max_length=64),
        ),
        migrations.AddField(
            model_name='stock',
            name='item_code',
            field=models.CharField(default='AISAT/CSE/AA/BBB', max_length=64),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(choices=[('CLS_1', 'Classroom 1'), ('LAB_1', 'Laboratory 1'), ('CSSTF', 'Computer Science Staff Room')], default='LAB_1', max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
