# Generated by Django 5.0.2 on 2024-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_rename_auditdetails_auditdetail_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.CharField(default='Computer', max_length=256),
            preserve_default=False,
        ),
    ]
