# Generated by Django 5.0.2 on 2024-05-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_computer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(choices=[('CLS_1', 'Classroom 1'), ('LAB_1', 'Laboratory 1'), ('LAB_2', 'Laboratory 2')], default='LAB_1', max_length=5),
        ),
    ]
