# Generated by Django 5.0.2 on 2024-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_alter_stock_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='type',
        ),
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('ELC', 'Electronics'), ('FUR', 'Furniture')], default='ELC', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditdetail',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('AVRG', 'Average'), ('BRKN', 'Bad')], max_length=4),
        ),
        migrations.DeleteModel(
            name='StockType',
        ),
    ]
