# Generated by Django 5.0.2 on 2024-05-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user',
            new_name='auditor',
        ),
    ]
